name: igprivateapi
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/kume1a/igprivateapi

environment:
  sdk: ^3.4.0

dependencies:

dev_dependencies:
  flutter_lints: ^3.0.1
  test: ^1.24.0
